### ISSUE TITLE
Wrong Object Type for Keys

### ISSUE THREAD

**Issue by rmbkucenski** [okta/samples-php#42]
I may be doing something wrong but I ran into an issue with the jwt-verifier where it didn't like the object type being passed in.  I'm running PHP 7.4 which may be stricter.

vendor/okta/jwt-verifier/src/JwtVerifier.php

```
$keys = $this->adaptor->getKeys($this->metaData->jwks_uri);

        foreach($keys as $id => $key) {
            $keys[$id] = new Key($key, 'RS256');
        }
        $decoded =  $this->adaptor->decode($jwt, $keys);
```
        
If I don't convert the items explicitly to the Key type I get an error because the array is a list of: OpenSSL key resource

Which seems to be coming from the use of

openssl_pkey_get_public

which is in 

vendor/okta/jwt-verifier/src/Adaptors/FirebasePhpJwt.php

in the parseKey function

**Comment by arvindkrishnakumar-okta** [comment]
@rmbkucenski Thanks for posting!

@bretterer can you help take a look?

**Comment by ghost** [comment]
This is likely caused by an update of our jwt validator library, so casting is the way to handle this. Sorry for the confusion here.

As for now, we have recently announced that our php libraries are placed in security path only mode and will be archived soon. If you have any further questions, please direct them over to our dev forum or develpers@okta.com
