### ISSUE TITLE
Tutorial is incompatible with default authorization servers - okta-hosted-login

### ISSUE THREAD

**Issue by agawronski** [okta/samples-php#46]
https://github.com/okta/samples-php/tree/develop/okta-hosted-login

This tutorial uses a default authorization server, which works in a free okta dev account. However it depends on okta-jwt-verifier-php which is incompatible with default authorization server in a production account. 

It is unclear to me how that is possible, but I am looking for a recommendation on how to set up authentication with OIDC, OKTA, PHP, and the default authorization server, in a production environment.

Can you point me to documentation, or a code example that will work for my use case?

Thanks,
Aidan.

**Comment by agawronski** [comment]
@bretterer @vijetmahabaleshwar-okta @ivanezeigbo-okta is it possible to get pointed in the right direction?

**Comment by ghost** [comment]
@agawronski, Unfortunately, the PHP libraries for JWT Verifier are not compatible with the default authorization server. The packages were built for the custom authorization server setup.

Since this ticket was created, we have announced that our PHP libraries are in security path only mode and will be archived soon. If you have any other questions, please feel free to reach out on our developer forum or developers@okta.com
